apiVersion: v1
kind: Service
metadata:
  name: user-interface-service
  namespace: servak-app
spec:
  selector:
    app: user-interface-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8001
  type: ClusterIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-interface-service
  namespace: servak-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user-interface-service
  template:
    metadata:
      labels:
        app: user-interface-service
    spec:
      containers:
        - name: user-interface-service
          image: markbro69/user_interface_service:latest
          ports:
            - containerPort: 8001
          env:
            - name: DATABASE_URL
              value: "mongodb://mongo:27017"
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: "kafka:9092"