apiVersion: apps/v1
kind: Deployment
metadata:
  name: nfs-server
  namespace: servak-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nfs-server
  template:
    metadata:
      labels:
        app: nfs-server
    spec:
      initContainers:
      - name: setup-nfs
        image: busybox
        command: ["sh", "-c", "mkdir -p /var/www/nfsshare && chmod 777 /var/www/nfsshare"]
        volumeMounts:
        - name: nfs-data
          mountPath: /var/www/nfsshare
      containers:
      - name: nfs-server
        image: itsthenetwork/nfs-server-alpine
        ports:
        - name: nfs
          containerPort: 2049
        - name: mountd
          containerPort: 20048
        - name: rpcbind
          containerPort: 111
        securityContext:
          privileged: true
        volumeMounts:
        - name: nfs-data
          mountPath: /var/www/nfsshare
        env:
        - name: SHARED_DIRECTORY
          value: /var/www/nfsshare
      volumes:
      - name: nfs-data
        hostPath:
          path: /var/www/nfsshare
          type: DirectoryOrCreate

---
apiVersion: v1
kind: Service
metadata:
  name: nfs-server
  namespace: servak-app
spec:
  ports:
  - name: nfs
    port: 2049
  - name: mountd
    port: 20048
  - name: rpcbind
    port: 111
  selector:
    app: nfs-server
  clusterIP: 10.96.0.100
