# pv-media.yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: media-pv
  namespace: servak-app
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 1Gi
  storageClassName: manual
  nfs:
    path: /
    server: 10.244.3.5
  mountOptions:
    - nfsvers=4.1
  persistentVolumeReclaimPolicy: Retain

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-pvc
  namespace: servak-app
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: manual
  resources:
    requests:
      storage: 1Gi