# pv-static.yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: static-pv
  namespace: servak-app
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 1Gi
  storageClassName: manual
  hostPath:
    path: "/mnt/data/static"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: static-pvc
  namespace: servak-app
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: manual
  resources:
    requests:
      storage: 1Gi