apiVersion: v1
kind: Pod
metadata:
  name: nfs-client
  namespace: servak-app
spec:
  containers:
  - name: nfs-client
    image: alpine:latest
    command: ["/bin/sh"]
    args:
      - "-c"
      - "sleep 3600"
    securityContext:
      privileged: true
    volumeMounts:
    - name: nfs-mount
      mountPath: /mnt
  volumes:
  - name: nfs-mount
    emptyDir: {}