apiVersion: v1
kind: Service
metadata:
  name: users-service
  namespace: servak-app
spec:
  selector:
    app: users-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8002
  type: ClusterIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-service
  namespace: servak-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: users-service
  template:
    metadata:
      labels:
        app: users-service
    spec:
      containers:
        - name: consume-notifications
          image: markbro69/users_service:latest
          securityContext:
            privileged: true
          command: [ "python", "manage.py", "consume_notifications" ]
        - name: users-service
          image: markbro69/users_service:latest
          ports:
            - containerPort: 8002
          env:
            - name: DATABASE_URL
              value: "mongodb://mongo:27017"
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: "kafka:9092"
          volumeMounts:
            - mountPath: /static
              name: static-volume
            - mountPath: /media
              name: media-volume
      volumes:
        - name: static-volume
          persistentVolumeClaim:
            claimName: static-pvc
        - name: media-volume
          persistentVolumeClaim:
            claimName: media-pvc
