apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: servak-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: markbro69/nginx:latest
        securityContext:
          privileged: true
        ports:
        - containerPort: 80
        volumeMounts:
          - mountPath: /static
            name: static-volume
          - mountPath: /media
            name: media-volume
      volumes:
        - name: static-volume
          persistentVolumeClaim:
            claimName: static-pvc
        - name: media-volume
          persistentVolumeClaim:
            claimName: media-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: servak-app
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80