apiVersion: v1
kind: Service
metadata:
  name: chats-service
  namespace: servak-app
spec:
  selector:
    app: chats-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8004
  type: ClusterIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: chats-service
  namespace: servak-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app:  chats-service
  template:
    metadata:
      labels:
        app: chats-service
    spec:
      containers:
        - name: chats-service
          image: markbro69/chats_service:latest
          ports:
            - containerPort: 8004
          env:
            - name: DATABASE_URL
              value: "mongodb://mongo:27017"
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: "kafka:9092"
          volumeMounts:
            - mountPath: /static
              name: static-volume
            - mountPath: /media
              name: media-volume
      volumes:
        - name: static-volume
          persistentVolumeClaim:
            claimName: static-pvc
        - name: media-volume
          persistentVolumeClaim:
            claimName: media-pvc
