apiVersion: v1
kind: Service
metadata:
  name: kafka
  namespace: servak-app
spec:
  ports:
    - port: 9092
      name: kafka
  clusterIP: None
  selector:
    app: kafka

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka
  namespace: servak-app
spec:
  serviceName: "kafka"
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
      - name: kafka
        image: wurstmeister/kafka:latest
        ports:
        - containerPort: 9092
        env:
        - name: KAFKA_ADVERTISED_LISTENERS
          value: "PLAINTEXT://kafka-0.kafka.servak-app.svc.cluster.local:9092"
        - name: KAFKA_LISTENER_SECURITY_PROTOCOL
          value: PLAINTEXT
        - name: KAFKA_LISTENER_PORT
          value: "9092"
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: "zookeeper:2181"
        - name: KAFKA_LISTENERS
          value: "PLAINTEXT://0.0.0.0:9092"
        - name: KAFKA_LISTENER_NAME
          value: "PLAINTEXT"
        - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
          value: "PLAINTEXT:PLAINTEXT"
        - name: KAFKA_LISTENER_NAMES
          value: "PLAINTEXT"
        - name: KAFKA_LISTENER_PORTS
          value: "9092"
        - name: KAFKA_LISTENER_HOSTS
          value: "0.0.0.0"
        - name: KAFKA_BROKER_ID
          value: "1"
        volumeMounts:
        - name: data
          mountPath: /var/lib/kafka/data
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 1Gi
